// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔒 HARDCODED FALLBACK to prevent URL corruption from browser extensions
const FALLBACK_SUPABASE_URL = 'https://tpmynhukocnyggqkxckh.supabase.co';

let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if URL is corrupted or missing and use fallback
if (!SUPABASE_URL || !SUPABASE_URL.includes('tpmynhukocnyggqkxckh') || SUPABASE_URL.includes('.ggg')) {
  console.warn('⚠️ Supabase URL missing or corrupted, using hardcoded fallback');
  SUPABASE_URL = FALLBACK_SUPABASE_URL;
}

// 🛡️ Intercept fetch to prevent URL corruption by browser extensions
const originalFetch = window.fetch;
window.fetch = function(...args) {
  let [resource, config] = args;
  
  // Fix corrupted Supabase URLs
  if (typeof resource === 'string') {
    // Check for corrupted URL patterns
    if (resource.includes('.ggg') || (resource.includes('supabase.co') && !resource.includes('tpmynhukocnyggqkxckh'))) {
      console.warn('🛡️ Intercepted corrupted Supabase URL:', resource);
      // Replace with correct URL
      resource = resource.replace(/tpmynhukocny\.gggkxckh\.supabase\.co/g, 'tpmynhukocnyggqkxckh.supabase.co');
      console.log('✅ Fixed URL to:', resource);
    }
  }
  
  return originalFetch.call(this, resource, config);
};

// Always log Supabase config (for debugging in production)
console.log('🔧 Supabase Config Check:', {
  url: SUPABASE_URL ? SUPABASE_URL : '❌ MISSING',
  urlPreview: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 40)}...` : 'N/A',
  keyExists: SUPABASE_PUBLISHABLE_KEY ? '✅ SET' : '❌ MISSING',
  keyPreview: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 25)}...` : 'N/A',
  isCorrectProject: SUPABASE_URL?.includes('tpmynhukocnyggqkxckh') ? '✅ CORRECT' : SUPABASE_URL?.includes('qsivfrgtncdvxvawgdbu') ? '❌ OLD PROJECT' : '❓ UNKNOWN',
  usingFallback: SUPABASE_URL === FALLBACK_SUPABASE_URL ? '⚠️ YES' : '✅ NO',
  fetchInterceptorActive: '✅ YES',
});

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase environment variables are missing!', {
    VITE_SUPABASE_URL: SUPABASE_URL ? 'SET' : 'MISSING',
    VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY || '', 
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
  }
);